INSERT INTO projects (title) VALUES ("Project 1");
INSERT INTO projects (title) VALUES ("Project 2");
INSERT INTO projects (title) VALUES ("Project 3");
INSERT INTO projects (title) VALUES ("Project 4");
INSERT INTO projects (title) VALUES ("Project 5");
INSERT INTO projects (title) VALUES ("Project 6");
INSERT INTO projects (title) VALUES ("Project 7");
INSERT INTO projects (title) VALUES ("Project 8");
INSERT INTO projects (title) VALUES ("Project 9");
INSERT INTO projects (title) VALUES ("Project 10");

INSERT INTO users (name) VALUES ("User 1");
INSERT INTO users (name) VALUES ("User 2");
INSERT INTO users (name) VALUES ("User 3");
INSERT INTO users (name) VALUES ("User 4");
INSERT INTO users (name) VALUES ("User 5");
INSERT INTO users (name) VALUES ("User 6");
INSERT INTO users (name) VALUES ("User 7");
INSERT INTO users (name) VALUES ("User 8");
INSERT INTO users (name) VALUES ("User 9");
INSERT INTO users (name) VALUES ("User 10");
INSERT INTO users (name) VALUES ("User 11");
INSERT INTO users (name) VALUES ("User 12");
INSERT INTO users (name) VALUES ("User 13");
INSERT INTO users (name) VALUES ("User 14");
INSERT INTO users (name) VALUES ("User 15");
INSERT INTO users (name) VALUES ("User 16");
INSERT INTO users (name) VALUES ("User 17");
INSERT INTO users (name) VALUES ("User 18");
INSERT INTO users (name) VALUES ("User 19");
INSERT INTO users (name) VALUES ("User 20");

INSERT INTO pledges (amount) VALUES (1);
INSERT INTO pledges (amount) VALUES (2);
INSERT INTO pledges (amount) VALUES (3);
INSERT INTO pledges (amount) VALUES (4);
INSERT INTO pledges (amount) VALUES (5);
INSERT INTO pledges (amount) VALUES (6);
INSERT INTO pledges (amount) VALUES (7);
INSERT INTO pledges (amount) VALUES (8);
INSERT INTO pledges (amount) VALUES (9);
INSERT INTO pledges (amount) VALUES (10);
INSERT INTO pledges (amount) VALUES (11);
INSERT INTO pledges (amount) VALUES (12);
INSERT INTO pledges (amount) VALUES (13);
INSERT INTO pledges (amount) VALUES (14);
INSERT INTO pledges (amount) VALUES (15);
INSERT INTO pledges (amount) VALUES (16);
INSERT INTO pledges (amount) VALUES (17);
INSERT INTO pledges (amount) VALUES (18);
INSERT INTO pledges (amount) VALUES (19);
INSERT INTO pledges (amount) VALUES (20);
INSERT INTO pledges (amount) VALUES (11);
INSERT INTO pledges (amount) VALUES (12);
INSERT INTO pledges (amount) VALUES (13);
INSERT INTO pledges (amount) VALUES (14);
INSERT INTO pledges (amount) VALUES (15);
INSERT INTO pledges (amount) VALUES (16);
INSERT INTO pledges (amount) VALUES (17);
INSERT INTO pledges (amount) VALUES (18);
INSERT INTO pledges (amount) VALUES (19);
INSERT INTO pledges (amount) VALUES (20);
